#! /usr/bin/python3
import os
import argparse
import subprocess


tool_dir = '/opt/pyplot/tools'
type_choices = ('line', 'bar', 'box', 'cdf', 'hist', 'surface', 'pie')


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('config', help="path to plot YAML file")
    parser.add_argument('-type', help='type of plot', choices=type_choices, default=None)
    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    if not os.path.isfile(args.config):
        print('Error: config file not found')
        return
    yaml_file = args.config
    plot_type = args.type
    if plot_type is None:
        name = os.path.basename(yaml_file)
        for c in type_choices:
            if c in name:
                print(f'selecting plot type {c}')
                plot_type = c
                break
    tool_script_path = os.path.join(tool_dir, f'{plot_type}.py')
    cmd = ['/usr/bin/python3', tool_script_path, yaml_file]
    cmd = ' '.join(cmd)
    print(cmd)
    subprocess.run(cmd, shell=True)
    print('done')


if __name__ == '__main__':
    main()
